In [42]:
import pandas as pd
docs = pd.read_csv("spacenews.csv")['content'][:2]


In [43]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

In [44]:
print(vectorizer.get_feature_names_out())
print(X.toarray())


['10' '11' '12' '13' '18' '20' '2017' '2019' '2025' '2026' '21' '360'
 '368' '58' '60' 'ability' 'able' 'about' 'achieve' 'achieving' 'acquired'
 'acquisition' 'added' 'additional' 'adjacent' 'advanced' 'advisor'
 'aerospace' 'affecting' 'after' 'against' 'ago' 'agreement' 'all'
 'allows' 'also' 'although' 'altogether' 'an' 'analytics' 'and'
 'announced' 'announcement' 'another' 'any' 'applications' 'are' 'areas'
 'argued' 'around' 'artificial' 'as' 'assets' 'at' 'aug' 'available'
 'aviation' 'away' 'balance' 'band' 'based' 'be' 'been' 'being' 'believe'
 'best' 'better' 'between' 'bid' 'big' 'biggest' 'billion' 'bit'
 'blackrock' 'block' 'board' 'boeing' 'both' 'brings' 'broadband'
 'broader' 'budget' 'built' 'bullet' 'burst' 'business' 'businesses' 'but'
 'buy' 'by' 'cabling' 'call' 'can' 'capabilities' 'capability' 'capacity'
 'capital' 'case' 'cash' 'caught' 'ceo' 'ceos' 'certain' 'certainly'
 'challenges' 'change' 'changes' 'chief' 'choice' 'civil' 'claim'
 'clarity' 'clearing' 'cl

In [45]:
len(vectorizer.get_feature_names_out())


779

In [46]:
# Initialize CountVectorizer with different n-gram parameters
for ngram_range in [(1, 2), (2, 2), (2, 3)]:
    vectorizer = CountVectorizer(ngram_range=ngram_range)
    X = vectorizer.fit_transform(docs)
    print(f"ngram_range={ngram_range}:")
    print("Feature Names:", vectorizer.get_feature_names_out())
    print("Tokens:")
    print(X.toarray())
    print("Number of tokens:", X.toarray().shape[1])
    print("=" * 50)

ngram_range=(1, 2):
Feature Names: ['10' '10 years' '11' ... 'your take' 'zealand' 'zealand the']
Tokens:
[[0 0 0 ... 0 1 1]
 [2 2 1 ... 1 0 0]]
Number of tokens: 2819
ngram_range=(2, 2):
Feature Names: ['10 years' '11 ka' '12 announcement' ... 'your leadership' 'your take'
 'zealand the']
Tokens:
[[0 0 0 ... 0 0 1]
 [2 1 1 ... 1 1 0]]
Number of tokens: 2040
ngram_range=(2, 3):
Feature Names: ['10 years' '10 years but' '10 years of' ... 'your take on' 'zealand the'
 'zealand the company']
Tokens:
[[0 0 0 ... 0 1 1]
 [2 1 1 ... 1 0 0]]
Number of tokens: 4420


In [47]:


# Initialize CountVectorizer with min_df=1
vectorizer_min_df_1 = CountVectorizer(min_df=1)
X_min_df_1 = vectorizer_min_df_1.fit_transform(docs)

# Initialize CountVectorizer with min_df=2
vectorizer_min_df_2 = CountVectorizer(min_df=2)
X_min_df_2 = vectorizer_min_df_2.fit_transform(docs)

# Number of tokens with min_df=1
num_tokens_min_df_1 = X_min_df_1.shape[1]

# Number of tokens with min_df=2
num_tokens_min_df_2 = X_min_df_2.shape[1]

# Initialize CountVectorizer with max_df=1
vectorizer_max_df_1 = CountVectorizer(max_df=1)
X_max_df_1 = vectorizer_max_df_1.fit_transform(docs)

# Initialize CountVectorizer with max_df=2
vectorizer_max_df_2 = CountVectorizer(max_df=2)
X_max_df_2 = vectorizer_max_df_2.fit_transform(docs)

# Number of tokens with max_df=1
num_tokens_max_df_1 = X_max_df_1.shape[1]

# Number of tokens with max_df=2
num_tokens_max_df_2 = X_max_df_2.shape[1]

print(f"Number of tokens with min_df=1: {num_tokens_min_df_1}")
print(f"Number of tokens with min_df=2: {num_tokens_min_df_2}")
print(f"Number of tokens with max_df=1: {num_tokens_max_df_1}")
print(f"Number of tokens with max_df=2: {num_tokens_max_df_2}")


Number of tokens with min_df=1: 779
Number of tokens with min_df=2: 151
Number of tokens with max_df=1: 628
Number of tokens with max_df=2: 779


In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(norm=None,min_df=2)
X = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['12' '20' 'about' 'ago' 'all' 'also' 'although' 'an' 'and' 'another'
 'applications' 'are' 'as' 'at' 'be' 'been' 'being' 'both' 'business'
 'but' 'by' 'can' 'capabilities' 'capital' 'chief' 'company' 'conference'
 'conservative' 'continue' 'could' 'customers' 'data' 'demand' 'didn'
 'different' 'do' 'doesn' 'felt' 'for' 'frequency' 'from' 'future' 'get'
 'go' 'going' 'good' 'great' 'has' 'have' 'he' 'him' 'if' 'in' 'initial'
 'interview' 'into' 'is' 'issue' 'it' 'its' 'just' 'last' 'later' 'launch'
 'leverage' 'like' 'lot' 'make' 'market' 'may' 'mix' 'money' 'months'
 'more' 'move' 'much' 'need' 'next' 'not' 'now' 'of' 'officer' 'on' 'one'
 'or' 'orbit' 'other' 'our' 'out' 'over' 'paris' 'plan' 'plans' 'point'
 'position' 'possible' 'potentially' 'products' 'put' 're' 'reached'
 'right' 'rushing' 'said' 'satellite' 'satellites' 'service' 'since'
 'smaller' 'so' 'some' 'still' 'such' 'tenets' 'term' 'than' 'that' 'the'
 'their' 'them' 'then' 'there' 'they' 'think' 'this' 'those' 'three

In [49]:


# Get the feature names (tokens)
feature_names = vectorizer.get_feature_names_out()

# Convert the TF-IDF matrix to a dense array for easier manipulation
tfidf_matrix = X.toarray()

# Find the index of the token with the highest TF-IDF value in each document
max_tfidf_indices = tfidf_matrix.argmax(axis=1)

# Get the token with the largest TF-IDF value in each document
for doc_index, max_index in enumerate(max_tfidf_indices):
    token = feature_names[max_index]
    tfidf_value = tfidf_matrix[doc_index, max_index]
    print(f"Document {doc_index + 1}: Token '{token}' has the largest TF-IDF value of {tfidf_value:.2f}")


Document 1: Token 'the' has the largest TF-IDF value of 47.00
Document 2: Token 'the' has the largest TF-IDF value of 85.00


In [51]:
import numpy as np
docs = pd.read_csv("spacenews.csv")['content']
vectorizer = TfidfVectorizer(stop_words = 'english', max_df=0.2)
X = vectorizer.fit_transform(docs)
indices = np.arange(docs.size)
from sklearn.model_selection import train_test_split
train, test = train_test_split(indices, test_size=0.2)
from sklearn.metrics.pairwise import cosine_distances
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=3,metric=cosine_distances).fit(X[train])
test=[test[0]]
found = nbrs.kneighbors(X[test], return_distance=False)
test_i=0
print('text:\n%.300s'%docs[test[test_i]])
for i in found[0]:
    print('match %d:\n%.300s'%(i,docs[train[i]]))



text:
WASHINGTON — As India prepares to launch its second lunar lander mission, the fate of a second Israeli lander is in doubt after the organization developing it lost a major source of funding. India’s Chandrayaan-3 spacecraft is scheduled to launch July 14 on a Geosynchronous Satellite Launch Vehicle 
match 286:
HELSINKI — India will make its second moon landing attempt in 18 days’ time after its Chandrayaan-3 spacecraft arrived in lunar orbit Saturday. Chandrayaan-3 began a roughly 30-minute burn around 9:30 a.m. Eastern, seeing the spacecraft enter an elliptical lunar orbit, the Indian Space Research Orga
match 700:
HELSINKI — India’s Chandrayaan-3 lander successfully touched down on the moon Wednesday, making the country only the fourth to achieve the feat. The Chandrayaan-3 mission lander touched down in the vicinity of the lunar South Pole region at 8:32 a.m. Eastern (1232 UTC) Aug. 23 after a 19-minute powe
match 450:
WASHINGTON — The technical success of India’s Chandrayaan-